# Generated by Django 5.2 on 2025-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_siteconfig_color_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_we_love',
            field=models.BooleanField(default=False),
        ),
    ]
